### ISSUE TITLE
Dragon Quest Heroes 2 PCSG00820 cheat hp,mp,sp not working

### ISSUE THREAD

**Issue by Peoples00** [r0ah/vitacheat#101]
hello i have a problem with dragon quest heroes 2 PCSG00820 and the cheats are not working and i am using the nonpdrm version the update is also installed 1.09

**Comment by xWillshady187x** [comment]
I have the same problem. They were working on my pstv the first few time, they stopped working

**Comment by Peoples00** [comment]
for me the cheats do not work there is MAI05 load but Maidump does not recognize the nonpdrm game

**Comment by xWillshady187x** [comment]
There’s  a video on YouTube that shows a guy using the cheats. I download it and most of them works. Just the first onesies  to seen to work. The other worked fine

**Comment by Peoples00** [comment]
yes I downloaded it and the cheats only work the first cheat hp, mp, sp does not work

**Comment by xWillshady187x** [comment]
Hey. The cheat does work. U need to get to the first city and they will work after that. I just got there and they now work

**Comment by Peoples00** [comment]
and what level are you at?

**Comment by Peoples00** [comment]
ok now it works

**Comment by SaiyanFantasyX** [comment]
How did you get it to work? 
I've managed to get crashes and weird audio effects when trying them out but never the intended result.
