### ISSUE TITLE
cheat resident evil revelation 2 (PCSH00187) not working

### ISSUE THREAD

**Issue by cendolinside123** [r0ah/vitacheat#104]
So I play this game using gamecard, but cheat not working 

Please complete the following information:**
 - **PSVita Firmware version**: 3.65Enso
 - **ID**: PCSH00187
 - **Version**: 1.0.4
 - **Type**: NoNpDrm (actualy I play it using game card)

**Comment by Yohoki** [comment]
These codes are for the MAI type. They are not compatible with NoNpDRM/GameCart. They will have to e remade. If you like, you can upload new codes as you find them or make a request at the forum: https://gbatemp.net/threads/vitacheat-finalcheat-database.485343/

I would recommend the forum, either way. Not many people look here. :)
