### ISSUE TITLE
Plugin causing error C2-12828-1

### ISSUE THREAD

**Issue by luckylew** [r0ah/vitacheat#106]
The plugin seems to cause error **C2-12828-1** for any game that I have cheats installed for.

**Comment by Yohoki** [comment]
In the .psv files for your games, do any of the codes start with "_V1" instead of "_V0"?

**Comment by luckylew** [comment]
No. They all start with _V0.

**Comment by Yohoki** [comment]
C2-12828-1 is a really generic error, and lots of things can cause it, unfortunately. Anything from plugins installed wrong, to corrupted mem cards. I'd ask on the GBAtemp forum's vitacheat thread. There's plenty of people that are active there, and this is more of a place to submit new codes, so you're not likely to get much help here. Here's the link to the thread. Sorry I can't help much more than that.

https://gbatemp.net/threads/vitacheat-finalcheat-database.485343
