### ISSUE TITLE
Digimon cyber sleuth Hackers memory EUR version

### ISSUE THREAD

**Issue by alvinceh** [r0ah/vitacheat#11]
Can i just use the code from US version?
Game code PCSB01183

Type of game: i install it using pkgi apps vita

**Comment by RikuNoctis** [comment]
You could try to see if it works and report back.

Some codes for a certain region do work for other regions, so you don't really lose anything by testing it yourself. Just make sure you name your .PSV correctly so it shows up on Vitacheat on your version of the game.

If it worked, you can report back here to confirm for everyone else. If if doesn't you can also report back, and maybe someone else can help to find the whole codes again but for the EU version, or even better, port the ones already here by finding the offsets.

**Comment by alvinceh** [comment]
not working, i just download the PCSE01171 (digimon US version) and rename the file to PCSB01183

and i try to activate the cheat and not working

i try the infinite yen and max ABI

just wonder how to create our own cheat? is there any tutorial i can refer? Thanks in advance

**Comment by RikuNoctis** [comment]
Check the [Wiki here](https://github.com/r0ah/vitacheat/wiki).

There are some tips and a couple of useful tutorials that can help you. You could also check the gbaTemp thread where a lot of users offer advice, and you can also read the previous posts where they describe their findings on various games.

**Comment by alvinceh** [comment]
Wow i just read the tutorial, very complicated for me as im not a usual in coding thing, guess gonna wait someone to port to EUR version

Thank you very much for your reply

**Comment by r0ah** [comment]
Shame that it didn't worked but why not just download the USA version then you can import your EUR savedata? That's what I did when I upgraded to NoNpDrm from Vitamin/MaiDump.

**Comment by alvinceh** [comment]
I dont know how to import my save data EUR to US? Do you have any tutorial of how to do the conversion? Really appreciate for your help
