### ISSUE TITLE
VitaCheat 3.73 Plugin Please!!!

### ISSUE THREAD

**Issue by Atayo57** [r0ah/vitacheat#110]
~~~~
# ID: PCSExxxxx
# Title:
# Region:
# Version:
# Type:
# Code Author:
# Credits:
# Source: https://github.com/r0ah/vitacheat/blob/master/db/PCSExxxxx.psv
# Note:
~~~~

**Comment by Yohoki** [comment]
This is only a database to store vitacheat codes. The creator of vitacheat does not visit this site.

Vitacheat (and many other plugins) don't work for 3.73. Please use Modoru to downgrade to 3.65.
