### ISSUE TITLE
Dragon Quest Builders PCSE00912 new material ID list submission

### ISSUE THREAD

**Issue by Bluevy** [r0ah/vitacheat#119]
Hi there,
The given wiki link below i believe the author using a google translate from mandarin to english.
This causes a problem as it causes inconvenience when i'm searching for a material's ID from the game description, and found a lot of them are mismatch.
Anyway I did a new compilation list on my own and hope the list help the other vitacheat users.

[DQ Builder.txt](https://github.com/r0ah/vitacheat/files/4499309/DQ.Builder.txt)

# ID: PCSE00912
# Title: Dragon Quest Builders
# Region: USA
# Version: 1.00
# Type: NoNpDrm
# Code Author: r0ah, Yohoki (Collosial Coffer Item Swap code)
# Credits: dask for the ITEM ID & EQUIPMENT ID tables (http://www.szhrfdz.com/534548/20663.html)
# Wiki: https://github.com/r0ah/vitacheat/wiki/PCSE00912

**Comment by eighthdayregret** [comment]
Wiki update completed. Thank you for your help.
Issue is now closed.
