### ISSUE TITLE
Needs Help with condition codes

### ISSUE THREAD

**Issue by asianking** [r0ah/vitacheat#121]
Can you show some examples of condition codes for base address pointers code?
Expected result: If the pointer base address contains a value of 10 or greater then run the codes below  

$3101 814000AC 0000F202
$3300 00000000 00000100

My guess would be:
$D600 814000AC 00000010, but the base address value is not or will not be correct. The value for base address is only to point where the pointers are located.

**Comment by eighthdayregret** [comment]
This is not an "issue," it is something that should have been asked in a forum, or somewhere else.
The only tip I can offer you would be to find out what the value would be _before_ the pointer address is populated. Typically, before you enter the game. As in, at the start menu, or something.
Then you'd use a "Not equal to" conditional.
For instance, if the value is usually 12345678 before the game fills in the pointer address, you'd want to use
$D502 814000AC 12345678
$3101 814000AC 0000F202
$3300 00000000 00000100
