### ISSUE TITLE
Playstation All-Star Battle Royale PCSA00069 Level 3 Super Power Cheat Code contribution

### ISSUE THREAD

**Issue by tokthem** [r0ah/vitacheat#14]
# ID: PCSA00069
# Title Playstation All-Star Battle Royale
# Region: EU

_V0 SuperPower
$0200 81B3BE78 45695A00

**Comment by r0ah** [comment]
Added to the [DB](https://github.com/r0ah/vitacheat/blob/master/PCSA00069.psv).
