### ISSUE TITLE
Game stuck at start screen

### ISSUE THREAD

**Issue by yovin** [r0ah/vitacheat#154]
some of my game cant start because of vitacheat (stuck at start screen image), if i delete vitacheat, the game can start normaly. What should i do? 

-Im using z06 on 3.65 vita

**Comment by eighthdayregret** [comment]
Check the codes to make sure they are not formatted in "On" status.
If that does not work, then it could be an issue with the game or plugin itself, which no one responsible for this repository is able to fix, as none of us created or maintain the plugin.
This is just a collection of tutorials and codes
