### ISSUE TITLE
Colorblind need help on font when activate cheat(s)

### ISSUE THREAD

**Issue by seriouswarhead** [r0ah/vitacheat#156]
**Describe your findings**
Hi, I'm having big trouble when try to activate cheat in VitaCheat z06. Cheat list's text front is clear and tiny but that's no problem for me.

My problen is when i press "Square" to activate but CAN'T see "Color changed" of font. So i don't know if that cheat been activate or not. So i have to go back & forth in-out the game to check which make me mad.

Is there anyway to change font color when activated and BOLD the font?

Device info:

VitaCheat z06 BETA for 3.65+ by FinalCheat, installed via AutoPlugins

VITA2000 moded HENkaku-2 3.65

Thank you very much in advance.

**Comment by eighthdayregret** [comment]
This is not an issue that is fixable by those responsible for maintaining this repository.
This issue lies in the programming of VitaCheat, which we cannot fix, as no one here created the plugin, only this code/tutorial repository.
