### ISSUE TITLE
PSM games not working

### ISSUE THREAD

**Issue by legomeaker101** [r0ah/vitacheat#157]
When pressing the shortcut for vitacheat within a Playstation Mobile game the vitacheat menu won't open.

 - **PSVita Firmware version**: 3.60Enso
 - **ID**: NPOA00172/NPOA00012/NPOA00013
 - **Version**: 1.00
 - **Type**: NoPsmDrm

**Comment by eighthdayregret** [comment]
PSM games are not supported by VitaCheat, and no one responsible for this repository can change that.
