### ISSUE TITLE
Not able to find correct values and game crashes

### ISSUE THREAD

**Issue by StamKaly** [r0ah/vitacheat#158]
**Describe the issue**
I am trying to "spawn" an item in my character's inventory in Terraria. 

After I have started the game with a new world and character, I try doing this by initiating a vitacheat search with the item ID of an item already in a specific slot in my inventory. Then by putting another item on that original slot I try making another search with the new item's ID to narrow the results down but they are 0. Even when changing the values that turn up on the original search, the game crashes instantaneously.

I have even tried to change the quantity of items I already had in my inventory to see if anything would work at all. That didn't work either and caused the game to crash when changing any values that turned up.

PS: 
1) I have performed all searches and changes of values in both 8-bit, 16-bit, 32-bit with no difference to the result (crashing) whatsoever.
2) If needed for testing purposes, the item IDs can easily be found online from [here](https://terraria.fandom.com/wiki/Item_IDs).
3) I have done this on the PC version of Terraria with Cheat Engine the same way I am trying to do it with vitacheat on PS Vita.
4) I am pretty confident that item IDs are universal among all platforms Terraria works on because exclusive items to a specific platform take up item IDs although they are not available on other platforms.

**Please complete the following information:**
 - **Your PSVita Firmware version**: 3.68h-encore
 - **ID**: PCSB-00405
 - **Version**: v365.z05
 - **Game Version**: 1.09 (Or UPFI-20160803 as shown on the title screen before the main menu)
 - **Type**: NoNpDrm

**Comment by eighthdayregret** [comment]
This is not an issue that anyone responsible for this repository can address, as it may pertain to the programming of the game or the plugin.
This is simply a repository and guide created by people who worked to figure out what codes they could.
