### ISSUE TITLE
Help for ragnarok odyssey ace asia ver.

### ISSUE THREAD

**Issue by Byorin** [r0ah/vitacheat#16]
I cannot find any any links to asia version maidump that has version 1.31 by chance do you have any links there? I really wanna play this one, I cannot use the cheats I only have non pdrm.

**Comment by r0ah** [comment]
[PCSH00044.psv](https://github.com/r0ah/vitacheat/blob/master/PCSH00044.psv)

**Comment by r0ah** [comment]
Wait, what? You were looking for the mai version but you have nonpdrm.
