### ISSUE TITLE
cheat code request

### ISSUE THREAD

**Issue by the-denzel** [r0ah/vitacheat#162]
# ID: PCSA00147
# Title: Freedom Wars
# Region: us

I'm looking for the psv file for this game but can't seem to find it anywhere, yet all the other versions have a cheat code file and this somewhat infuriates me.

**Comment by demur1** [comment]
> #

> # ID: PCSA00147
> # Title: Freedom Wars
> # Region: us
> I'm looking for the psv file for this game but can't seem to find it anywhere, yet all the other versions have a cheat code file and this somewhat infuriates me.

Porque no haces tu código?

**Comment by eighthdayregret** [comment]
No requests.
Not ever.
