### ISSUE TITLE
the shortcut right + L does not work on any games

### ISSUE THREAD

**Issue by hammurabi999** [r0ah/vitacheat#167]
**Note**:
Read the [Troubleshooting](https://github.com/r0ah/vitacheat/wiki/Troubleshooting) page before reporting any issues.

**Describe the issue**
when I launch a game and I make the shortcut nothing happens, I installed the plugin with auto plugin 2 and all the folders are ok

**Please complete the following information:**
 - **Your PSVita Firmware version**: Enso, 3.65Enso
 - **ID**: PCSF00446
 - **Version**: (the game version, if no update then it's 1.00)
 - **Type**:  NoNpDrm

**Comment by eighthdayregret** [comment]
This is a configuration issue in either config.txt or the placement of your plugins, which is common when installing just about anything using AutoPlugin.
Reinstall manually.
