### ISSUE TITLE
Digimon Story Cyber Sleuth: Hacker's Memory (PCSE01171) - New Code

### ISSUE THREAD

**Issue by KiraYamatoSD** [r0ah/vitacheat#17]
# ID: PCSE01171
# Title: Digimon Story Cyber Sleuth: Hacker's Memory
# Region: USA
# Version: 1.05
# Type: NoNpDrm
# Code Author: KiraYamatoSD
# Credits: r0ah
# Wiki: https://github.com/r0ah/vitacheat/wiki/GAMEID
# Source: https://github.com/r0ah/vitacheat/blob/master/GAMEID.psv
# Original Source:
# Note: Popular Guy's Guide - Gives 800000 exp to one digimon

_V0 Have Popular Guys Guide in Slot #1 [Note 1]
$D202 830D9335 00AC85E5
$0000 830C7CEC 000000D6
$0000 830C7CF4 00000063
$D202 82FD9335 00AC85E5
$0000 82FC7CEC 000000D6
$0000 82FC7CF4 00000063

_V0 #1: Sell existing Popular Guys Guide before activating the cheat
$0000 00000000 00000000

**Comment by r0ah** [comment]
[Added](https://github.com/r0ah/vitacheat/commit/1fbb251c2411bcf0c097c1d153ebce60b5e19309) to the DB.
