### ISSUE TITLE
Vitacheat breaking game save process, possible disable/blacklist?

### ISSUE THREAD

**Issue by pmsobrado** [r0ah/vitacheat#170]
Yesterday I tried the game Akiba's Trip and discovered that I cannot save. The game keeps "saving" forever. Searching the net, I found almost no info about it, except for two mentions here and there explaining that VitaCheat is the culprit and that it had to be completely removed from both ur0 and ux0 partitions. Apparently, it is not enough just to deactivate it. Also, it doesn't matter the dump type or region of the game.

After some trial and error, I discovered that it is the vitacheat.suprx file in ux0:/vitacheat the one that makes the game not to be able to save. vitacheat.skprx can be left enabled and the game will save as long as vitacheat.suprx is not in its path (and therefore not loaded, I guess).

So, my question is, is there a way to disable loading vitacheat.suprx for selected titles only? Some kind of blacklist? I tried creating an exception in ur0:/tai/config.txt for the title, so it won't load any plugins, but it does not work. I guess vitacheat.suprx is loaded in a different way.

 - **PSVita Firmware version**: 3.60HENkaku / Enso
 - **ID**: PCSE00428
 - **Version**: 1.00 I guess, no updates available
 - **Type**: NoNpDrm

**Comment by eighthdayregret** [comment]
Unfortunately, this is not the pace to ask for this, as no one who manages this repository has any hand in the actual programming of the VitaCheat plugin.
