### ISSUE TITLE
Deathmatch village

### ISSUE THREAD

**Issue by GalSen97** [r0ah/vitacheat#171]
Did you create the cheat code or you're only sharing it? Please specify it to avoid confusion. Also, do not forget to include the **Version** and **Type**! If you don't specify the version then I'll just assume it's for the base version which is 1.00. If no type is specified then I won't add your cheat code in the database until you specify it in the issue comments.	

## Testing tour Cheat Codes ##

Before you submit your cheat code you have to test it in this condition:

1. Close the game's bubble to restart the game then test your codes 
2. Do a full shutdown of your PSVita by holding the power button then test your codes

If cheat code doesn't work after doing all the steps then the game have DMA. Read the following pointer code tutorials:

* [Finding Pointers With TempAR](https://github.com/r0ah/vitacheat/wiki/Finding-Pointers-With-TempAR)
* [Finding Pointers With TempAR (Video)](https://github.com/r0ah/vitacheat/wiki/Finding-Pointers-With-TempAR-(Video))
* [Finding Multi-Level Pointers With TempAR](https://github.com/r0ah/vitacheat/wiki/Finding-Multi-Level-Pointers-With-TempAR)
* [Pointer Search Tips](https://github.com/r0ah/vitacheat/wiki/Pointer-Search-Tips)

## Formatting Description ##

* **Title**: Please use the NPS database for consistency!
* **Version**: Do not leave this blank! If no updates then it's 1.00. If the type is CompPack then input the CompPack's version instead.
* **Type**: Do not leave this blank either!
   * Vitamin
   * MaiDump
   * CompPack
   * NoNpDrm
* **Code Author:**: Are you the creator then add your name. Use credits if you're sharing other peoples work.
* **Credits**: For example you've implemented other people's work such as item tables, add them here with links to their work. Remove this if none.
* **Wiki**: If your cheat code have **in-game notes** then add this and I will add the wiki notes myself. Remove this if none.
* **Original Source**: This is the link to your website or thread where you **originally posted this cheat code**. Remove this if none.
* **Note**: This is the global notes, not in-game notes! If you want to add your findings or you have something you want to share with us, etc. Remove if none.

**Comment by eighthdayregret** [comment]
Please do not create an issue where you do not actually cite an issue that is fixable by those responsible for maintaining this repository.
Thank you.
