### ISSUE TITLE
Cyber Sleuth (pcse00755) max scan bug

### ISSUE THREAD

**Issue by rioM1** [r0ah/vitacheat#2]
The max scan cheat only works on a few digimons. Furthermore, it makes some digimon undiscoverable (ex:Kuramon) and thus unobtainable in that savegame.

Edit:Browsing through the game's memory, apparently digimon data is scattered to multiple sections, which would explain while some doesn't get covered by the cheat. As for the undiscoverable bug, it seems to be related to how the game check when to unlock new entry in the digimon list. If you digivolve  to one of the bugged digimons, its entry in the field guide and the lab will unlock fine with 200% scan. 

It's probably a good idea to find all the baby digimons first before you activate the cheat cause you can't de-digivolve to an undiscovered digimon. The earliest you can do this is chapter 1 after beating the bronze tournament for Kuramon.

Edit 2: After more testing, set the scan percentage to B4 (180) rather than C8(200) will work fine. Apparently, at max scan, digimon won't unlock properly. For people who already ran into the bug, change the code to B4 and hunt the digimon down again will fix it.

**Comment by rioM1** [comment]
Here is the code to cover the rest of the digimon for both version
Version 1:
_V0 - Max Scan v1[2]
$4000 83f9e642 000000B4 #SLOTS: 33 (DEC)
$0021 00000030 00000000 #LAST SLOT: 83f9ec42

_V0 - Max Scan v12[2]
$4000 83f99d52 000000B4 #SLOTS: 21 (DEC)
$0015 00000030 00000000 #LAST SLOT: 83f9A112

_V0 - Max Scan v13[2]
$4000 83f9e092 000000B4
$4000 83f9dfb2 000000B4
$4000 83f9df82 000000B4
$4000 83f9def2 000000B4
$4000 83f9dec2 000000B4
$4000 83f98b12 000000B4
$4000 83f98ae2 000000B4 #SLOTS: 7 (DEC)

Version 2: 
_V0 - Max Scan v2[2]
$4000 8409e642 000000B4 #SLOTS: 33 (DEC)
$0021 00000030 00000000 #LAST SLOT: 8409ec42

_V0 - Max Scan v22[2]
$4000 84099d52 000000B4 #SLOTS: 21 (DEC)
$0015 00000030 00000000 #LAST SLOT: 8409A112

_V0 - Max Scan v23[2]
$4000 8409e092 000000B4
$4000 8409dfb2 000000B4
$4000 8409df82 000000B4
$4000 8409def2 000000B4
$4000 8409dec2 000000B4
$4000 84098b12 000000B4
$4000 84098ae2 000000B4 #SLOTS: 7 (DEC)

**Comment by roahnosh** [comment]
Thanks for the info. I'll keep this open so others with similar issue can post here.

**Comment by KiraYamatoSD** [comment]
@rioM1 May I ask how can I use the above code that you have posted? 

Do I enable all of the version 1 or version 2 code together or separately? 

Also, v13 and v23 crashes the game when it is enabled.

**Comment by 0x6a6576** [comment]
_V0 Max Scan [Note 2]
$D202 840AD955 00AC85E5
$4000 83F9A282 000000B4 #SLOTS: 179 (DEC)
$00B3 00000030 00000000 #LAST SLOT: 83F9C3E2
$D202 841AD955 00AC85E5
$4000 8409A282 000000B4
$00B3 00000030 00000000 #LAST SLOT: 8409C3E2

_V0 Max Scan 2
$D202 840AD955 00AC85E5
$4000 83F99D52 000000B4
$0014 00000030 00000000
$D202 841AD955 00AC85E5
$4000 84099D52 000000B4
$0014 00000030 00000000

_V0 Max Scan 3
$D202 840AD955 00AC85E5
$4000 83F9A1D2 000000B4
$0002 00000030 00000000
$D202 841AD955 00AC85E5
$4000 8409A1D2 000000B4
$0002 00000030 00000000

_V0 Max Scan 4
$D202 840AD955 00AC85E5
$4000 83F9E642 000000B4
$0020 00000030 00000000
$D202 841AD955 00AC85E5
$4000 8409E642 000000B4
$0020 00000030 00000000

Try this instead. Just enable all.

**Comment by r0ah** [comment]
Updated the scan cheat code.

https://github.com/r0ah/vitacheat/commit/d6d979c3d85e2c5c4665bd1483c5eec03a76fb86
