### ISSUE TITLE
Berserk and the Band of the Hawk ps vita

### ISSUE THREAD

**Issue by ymbgames** [r0ah/vitacheat#21]
Game ID PCSE01034
Title Berserk and the Band of the Hawk
Game version 1.01
Game type NoNpDrm

new code
_V0 double slot MAX 
$0200 8747D144 00000005

**Comment by r0ah** [comment]
[Added](https://github.com/r0ah/vitacheat/commit/d135fccf0bdc4492603aacfd82d27cbeff5ad26c).
