### ISSUE TITLE
Fixed Infinite health not working and added new codes Mortal Kombat 2011

### ISSUE THREAD

**Issue by Demolinizer** [r0ah/vitacheat#25]
~~~~
# ID: PCSB00106
# Title: Mortal Kombat 
# Region: PAL/EU
# Version: 1.00
# Type: NoNpDrm
# Code Author: Demolinizer
# Note: Added X-Ray code in case the original PCSB00106 gets replaced with this one 

_V0 1P Infinite Health
$0200 8A735934 3F800000

_V0 P1 Infinite X-Ray
$0200 81F8CD3E 00003F80

_V0 Infinite Life Gauge 
$0200 8A735938 3F800000

_V0 Tag Match 1P Infinite Health
$0200 8A798B94 3F800000
~~~~

**Comment by r0ah** [comment]
[Added](https://github.com/r0ah/vitacheat/blob/master/PCSB00106.psv) to the DB.

**Comment by Smoker1** [comment]
Confirmed, Added and Adjusted Codes

_V1 Inf Time Smoker1
$0000 81F965AC 00000063

_V1 1P Inf Health Smoker1-Demolinizer
$0200 8A735934 3F800000

_V1 Inf Life Bar Blood Smoker1-Demolinizer
$0200 8A735938 3F800000

_V0 Tag Match 1P Infinite Health
$0200 8A798B94 3F800000

_V1 1P Inf X-Ray Smoker1-Demolinizer
$0200 81F8CD3C 3F800000

_V1 CPU No X-Ray Smoker1
$0200 81F8DB58 00000000

_V1 CPU Takes 2x Damage Smoker1
$0200 81F8DAEC 40000000

_V0 CPU Takes 3x Damage Smoker1
$0200 81F8DAEC 40400000

_V0 99999 Koins Smoker1
$0200 81FBBDF8 0001869F
