### ISSUE TITLE
uncharted.suprx (vosmans)

### ISSUE THREAD

**Issue by Demolinizer** [r0ah/vitacheat#29]
vosmans uncharted.suprx works in the PAL version of the game 
*PCSF00001
ur0:tai/uncharted.suprx
hold down on dpad to activate or down and triangle (mine is just down)

**Comment by r0ah** [comment]
Thanks for confirming. Updated [page](https://github.com/r0ah/vitacheat/wiki/How-to-Use-Cheat-Plugins/).

**Comment by Demolinizer** [comment]
no problems my friend going to keep testing the other plugins got a few more cheat database files to upload today too gotta keep you busy
