### ISSUE TITLE
more vosmans cheats working in the PAL versions of games Unit 13 wipeout 2048 and world of final fantasy

### ISSUE THREAD

**Issue by Demolinizer** [r0ah/vitacheat#30]
*PCSF00034
ur0:tai/unit13.suprx

*PCSF00007
ur0:tai/wo2048.suprx

*PCSB00951
ur0:tai/woff.suprx

**Comment by r0ah** [comment]
Thanks for confirming. Updated the wiki page.

https://github.com/r0ah/vitacheat/wiki/How-to-Use-Cheat-Plugins

**Comment by Demolinizer** [comment]
u didnt add unit 13 PAL to it mate just letting u know
