### ISSUE TITLE
didnt add unit 13 PAL (Vosmans) this is different to the existing one 

### ISSUE THREAD

**Issue by Demolinizer** [r0ah/vitacheat#32]
*PCSF00034
ur0:tai/unit13.suprx

*u also need to add PAL to the world of final fantasy one that i sent earlier

**Comment by r0ah** [comment]
Added unit13. Updated the wiki page. Woff is PCSB not PCSF tho.

Like this?
~~~~
*PCSB00951 #PAL
ur0:tai/woff.suprx
~~~~

**Comment by Demolinizer** [comment]
yea mate it should look like this 
*PCSB00951 #PAL
ur0:tai/woff.suprx

*PCSE00880 #NTSC
ur0:tai/woff.suprx
