### ISSUE TITLE
Help Stardew Valley PCSE01235

### ISSUE THREAD

**Issue by bimbims27** [r0ah/vitacheat#33]
why cheat didnt work ? i read the version of stardew valley is 1.02, but i can find where to download 1.02 version, can you help me ? i was downloaded from nopaystation browser, and i dont know what version of my stardew valley

**Comment by Demolinizer** [comment]
if that didnt work download the entire game through pkgj once that has finished make sure ur still highlighting the game and click L to install the compatability pack after that has finished click the game but dont start it wait for a bit and the orange download symbol should come up click that and wait till that finished once that done start ur game up

**Comment by Demolinizer** [comment]
no problems always here to help glad it worked
