### ISSUE TITLE
No Heroes Allowed (PCSF00531) - Plugin will not open

### ISSUE THREAD

**Issue by Yohoki** [r0ah/vitacheat#36]
Vitacheat does not appear when using the game "No Heroes Allowed: No Puzzles Either!". When pressing "L+Dpad Right", Vitacheat's black background tries to display, but disappears immediately. The game does not pause. The plugin menu is still up, because pressing "R+Dpad right" to close the plugin also shows a slight black flash as the plugin closes. This does not happen with any other dumps or apps I have, and the plugin functions normally anywhere else.

 - **Your PSVita Firmware version**: 3.68 h-encore
 - **ID**: PCSF00531
 - **Version**: 1.00
 - **Type**: NoNpDrm

**Comment by r0ah** [comment]
Seem like a compatibility issue. Maybe the next version of Vitacheat will fix this issue.

This also happens with Minecraft, Iconoclast, Axiom Verge.
