### ISSUE TITLE
Fat Princess - Piece of Cake (PCSF00612)

### ISSUE THREAD

**Issue by Yohoki** [r0ah/vitacheat#37]
~~~
# ID: PCSF00612 
# Title: Fat Princess-Piece of Cake
# Region: EU
# Version: 1.03
# Type: Mai / NoNpDRM / Vitamin (uses B200 for all codes)
# Code Author: Yohoki
# Source: https://github.com/r0ah/vitacheat/blob/master/PCSF00612.psv
# Note: You can change the last four numbers to place the amount you want. Change to a different screen and it will show the change.
# IMPORTANT: Game will not load if cheats are set to turn on automatically.

_V0 999 Coins
$B200 00000000 00000000
$0200 0310FD14 000003E7

_V0 99 Stamina
$B200 00000000 00000000
$0200 0310FCB8 00000063

_V0 Collect 1 Cake for Lvl 3 Cake Smash
$B200 00000000 00000000
$0200 0310FD30 00000063
$B200 00000000 00000000
$0200 031BC220 00000063

_V0 1500 Diamonds
$B200 00000000 00000000
$0200 0310FD08 000005DC

_V0 1M Damage Dealt
$B200 00000000 00000000
$0200 0310FD20 000F423F

_V0 Always Turn 1
$B200 00000000 00000000
$3201 04764EBC 000000B4
$3300 00000000 00000001
~~~

Powerups use pointers, and cannot easily be added as codes. Use Inf coins code to just buy them.

**Comment by BeemerDream** [comment]
First, thank you for this.
But it crashes when i test the first code.
Do you now why it doesn't work for me?

**Comment by BeemerDream** [comment]
Thank you! 😀
I think i have version 1.00 so i'll update later.

**Comment by BeemerDream** [comment]
So i've updated to 1.03, but the game still freezes.
I activate the cheats on the map screen and i've doublechecked that i've entered the right codes.
Thanks again, i appreciate your work.

**Comment by BeemerDream** [comment]
I've downloaded it from pkgj.
![dsc_0002](https://user-images.githubusercontent.com/40903972/49186646-83021b80-f365-11e8-9c25-5c5467bbcc8c.JPG)

**Comment by Yohoki** [comment]
Ah. Yours is not a MaiDump version. That looks like NoNpDRM version. Maybe @r0ah can confirm? I'm not familiar with the app you mentioned.

I will do another PSV for you and release it. I wouldn't say where you got it from, though. It's a free to download game, but that's probably still a no-no. Please delete your last comment and I'll have a new cheat list in a day or so.

**Comment by BeemerDream** [comment]
Yes, that's correct.
Deleted, sorry about that, and yes i know it's a free game but it's not available on PS store anymore.
Thank you, that would be great.

**Comment by Yohoki** [comment]
@BeemerDream , will you try this file for me?


~~~
# ID: PCSF00612 
# Title: Fat Princess-Piece of Cake
# Region: EU
# Version: 1.03
# Type: NoNpDRM
# Code Author: Yohoki
# Source: https://github.com/r0ah/vitacheat/blob/master/PCSF00612.psv
# Note: You can change the last four numbers to place the amount you want. Change to a different screen and it will show the change.
# IMPORTANT: Game will not load if cheats are set to turn on automatically.
# TEST FILE - DO NOT USE

_V0 999 Coins
$0200 8410FD14 000003E7

_V0 99 Stamina
$0200 8410FCB8 00000063

_V0 Collect 1 Cake for Lvl 3 Cake Smash
$0200 8410FD30 00000063
$0200 841BC220 00000063

_V0 1500 Diamonds
$0200 8410FD08 000005DC

_V0 1M Damage Dealt
$0200 8410FD20 000F423F
~~~

**Comment by BeemerDream** [comment]
Thank you, i'll try it after work😉 and get back to you.

**Comment by BeemerDream** [comment]
Thank you, it's working now.
Your'e the best.

**Comment by nighto** [comment]
Hi, couldn't get it work with plugin z04 and game version 1.03. I tried the codes one by one and they don't see to do anything, and if I switch all of them on, the game crashes. Do you have any suggestion that I could try to debug it? Thanks in advance.
