### ISSUE TITLE
Plants vs Zombies (PCSE00064)

### ISSUE THREAD

**Issue by Yohoki** [r0ah/vitacheat#39]
~~~~
# ID:  PCSE00064
# Title: Plants vs Zombies
# Region: US
# Version: 1.02
# Type: Mai, NoNpDRM, Vitamin (All codes use B200)
# Code Author: Yohoki
# Source: https://github.com/r0ah/vitacheat/blob/master/PCSE00064.psv
# Note: Made and tested on Mai version, but should work on all dumps.
# Note1: Change value of Sun only in increments of 5 or game will crash after completing round.

_V0 1M Coins B200
$B200 00000000 00000000
$3201 005FFB40 00000308
$3300 00000000 0001869F

_V0 Inf Sun b200
$B200 00000000 00000000
$3201 005F41AC 000055CC
$3300 00000000 00001388
~~~~

**Comment by 3750gustavo** [comment]
its crashing for me every time

**Comment by Yohoki** [comment]
What game version and how was yours dumped?

**Comment by 3750gustavo** [comment]
i fixed bye searching manually for the sun at 8c,however the address changes every time. i could t change the coins.

**Comment by Yohoki** [comment]
This game uses pointers. The codes will change every time you open the game unless you do a pointer search. Coins is not really what is shown. It is your coins divided by 10.

You also didn't answer what version and region you are using. I'd like to know so I can fix properly.

**Comment by 3750gustavo** [comment]
I'm using the USA version with update. How do i do the search for the coins ?


Em 3 de jan de 2019 14:33, Yohoki <notifications@github.com> escreveu:

This game uses pointers. The codes will change every time you open the game unless you do a pointer search. Coins is not really what is shown. It is your coins divided by 10.

You also didn't answer what version and region you are using. I'd like to know so I can fix properly.

**Comment by Yohoki** [comment]
If you have 100 coins, search 10 instead.

**Comment by 3750gustavo** [comment]
Thanks ,I will try , I really wanted to buy the expensive stuff from the store.

Em 3 de jan de 2019 15:04, Yohoki <notifications@github.com> escreveu:

If you have 100 coins, search 10 instead.

**Comment by 3750gustavo** [comment]
made it,thanks . you sure must have taken a really long time to find about the "10".

**Comment by r0ah** [comment]
Sorry for delay. Added to the DB.

**Comment by Luis8mem** [comment]
Could you also make the Code for Infinite Sun for the EU Version (PCSF00105) please?

**Comment by Luis8mem** [comment]
> Sorry for delay. Added to the DB.

Could you also make the Code for Infinite Sun for the EU Version (PCSF00105) please?

**Comment by yunes-0840** [comment]
made a 10 million coins cheat for the eu version (PCSF00105):

`$0200 86BE86C8 000F423F`

haven't done much testing but i turned the cheat on inside the zen garden then turned it off once it updated the coin meter
game limits it to 1 million though
