### ISSUE TITLE
Ys: memories of celceta

### ISSUE THREAD

**Issue by noranca90** [r0ah/vitacheat#5]
The cheat works but you have to turn it on and off for it to work if you leave it on for a couple minutes the game crashes any fix on that?

**Comment by noranca90** [comment]
Stardew valley also has the same issue idk if its just me

**Comment by roahnosh** [comment]
Youre playing SV on h.encore or lower firmware?

I'll check YS. Maybe it needs multi-level pointers.

**Comment by noranca90** [comment]
h encore
