### ISSUE TITLE
removed LIST.md

### ISSUE THREAD

**Issue by ONElua** [r0ah/vitacheat#53]
For Autoplugin you could use the checklist (Im gdljjrod)
https://raw.githubusercontent.com/r0ah/vitacheat/master/LIST.md
for download and update cheats.db

It is possible to return it or
give me a link to the base of cheats in the same way (list) to know the new ones that have gone up
Thank you

**Comment by r0ah** [comment]
Sorry for the late reply. I've re-uploaded and updated it.

**Comment by Yohoki** [comment]
Looks like this issue is fixed. I'll close it now.
