### ISSUE TITLE
Organize/reorder cheats

### ISSUE THREAD

**Issue by mirh** [r0ah/vitacheat#54]
I mean, maybe it's OCD, but hundreds of files and counting in a single folder (let alone the root) seems... *off*. 
For as much as, I guess this is not pcsx2, and you are still far from hitting the 1k limit of github's web view, I would say something a bit less clustered would be better. 

From the tip of my mind I couldn't come out with decisively "best" criteria to perform this division though. 
But I'd hope somebody could come up with a good idea.

**Comment by Yohoki** [comment]
It's pretty easy to search this list with Ctrl+F , and it's got all the info we need to do that, name and ID. Unless we get to the point where it's not able to display more titles, I wouldn't mess with it. The only way I can think or to even compress it a little is to put different versions of the same game (ie US, EU, JP) into a folder. Or to put entire series into one folder, like all Sword Art Online games together and such. I doubt either of these would reduce the number if listings very significantly, though.

**Comment by r0ah** [comment]
Sorry but we can't move the file (for now) as the history would be lost if I did. I kinda wanted to move them to the db directory since we now have the _plg_, but yeah, too late for that now, unless someone know how to re-merge  the history?

But who cares about the history anyway? Let see if I get a free time then I'll move the psv files to the db directory.

**Comment by mirh** [comment]
The history button in github doesn't, but blame [still](https://git.wiki.kernel.org/index.php/GitFaq#Why_does_Git_not_.22track.22_renames.3F) continues to show previous commits. 

Anyway, I guess this is already a huge improvement. 
...still, it's 481 files in a single folder..

**Comment by Yohoki** [comment]
O.O we lost all the names, though. XD

**Comment by r0ah** [comment]
@mirh I've tried many methods but I couldn't get to associate the history to individual files. Ah yes, I almost forgot about that button. You can also use `git log --follow` /  `git log --follow -p`. There's only 241 files inside the db.

@Yohoki I think that it's more important to use the full descriptions for real changes. I updated the [LIST.md](https://github.com/r0ah/vitacheat/blob/master/LIST.md) with links.

**Comment by Yohoki** [comment]
Ah. I see. That makes sense. Any possible way to include links in that file, then? That would keep people from having to look at one list then search through another.

**Comment by mirh** [comment]
I mean, can't you just search "game name" in the github search, and call it a day?

**Comment by Yohoki** [comment]
Actually, I see that Roah has already added links since I last looked at the LIST.md . Very good. I'm just dumb and didn't notice he mentioned already adding links.
