### ISSUE TITLE
Secret of Mana

### ISSUE THREAD

**Issue by VisitntX** [r0ah/vitacheat#56]
~~~~
# ID: PCSE01153
# Title: Secret of Mana
# Region: USA
# Version: 1.0
# Type: NoNpDrm
# Code Author: VisitntX
# Source: https://github.com/r0ah/vitacheat/blob/master/db/PCSE01153.psv
~~~~
_V0 Randy Infinite HP
$3201 82280064 0000073C
$3300 00000000 000000FF

_V0 Popoi Infinite HP
$3201 8177E954 00000108
$3300 00000000 000000FF

_V0 Prim Infinite HP
$3201 81ADEE88 00000C4C
$3300 00000000 000000FF

**Comment by r0ah** [comment]
Thanks for the submission. Added to the db.

**Comment by Kumokun5** [comment]
sir why it wont work?

**Comment by RikuNoctis** [comment]
> sir why it wont work?

Are you using a NA NoNpDrm dump on game version 1.0? Most of the time it's because of this; you aren't using the version of the game the codes were made for (some codes do work even between different versions, though).

**Comment by falcus123** [comment]
can you hack codes like these for Inf Energy/MP?the Hp codes are working perfectly!
