### ISSUE TITLE
[idea] rumble cheats support

### ISSUE THREAD

**Issue by eadmaster** [r0ah/vitacheat#59]
I'd like to suggest adding support for [rumble cheats like RetroArch recently did](https://docs.libretro.com/guides/cheat-codes/#retroarch-rumble-codes).

(obviously they're for [PSTV usage only](http://thevitalounge.net/forum/threads/do-any-games-actually-support-force-feedback-rumble-vibration.3967/))

**Comment by Yohoki** [comment]
That's an excellent idea. Unfortunately, this is only a database for sharing codes we have all made. r0ah can't add new features, as the creator doesn't make his source open on github. Send ideas his way at: https://github.com/Finalcheat/finalcheat.github.com/issues
