### ISSUE TITLE
Dragon Ball Z: Battle of Z

### ISSUE THREAD

**Issue by Peoples00** [r0ah/vitacheat#62]
hi the cheats of dragonball z battle of z pcsb00396 EU are not displayed in the cheat menu

**Comment by Yohoki** [comment]
I might have made a code name too long on accident when cleaning it all up. Let me take a look at it.

**Comment by Yohoki** [comment]
I guess we can't use X anymore to show that a code is a modifier. Try the new file.

**Comment by Peoples00** [comment]
thank you :)
do only the cards or the other cheats work?

**Comment by Yohoki** [comment]
All the cheats still work. I just changed the Cards from XXXXXXXX to "Fruit of the tree of might". Check the Wiki for details on how to put other cards in.

**Comment by Peoples00** [comment]
thank you :)

**Comment by Peoples00** [comment]
I have a problem and that goes infinite dragon points and infinite premium points that do not work

**Comment by Yohoki** [comment]
Are you on version 1.01?

**Comment by Peoples00** [comment]
yes

**Comment by Yohoki** [comment]
hmm... Ok. I'll take a look at it. I don't have a pointer code for those, so I'll see if there's a pointer moving them around.

**Comment by Peoples00** [comment]
Thank you for watching this

**Comment by Yohoki** [comment]
No problem. It's very late here tonight, though and I'm heading to bed. I'll look into this tomorrow.

**Comment by Peoples00** [comment]
good night

**Comment by Yohoki** [comment]
are you using a NoNpDRM version of DBZ?

I've tried to get the codes to move around, but none of the other codes for this game use a pointer so it'd be really weird if just these 2 did.

**Comment by Peoples00** [comment]
yes that's the nonpdrm version

**Comment by Yohoki** [comment]
That's strange... None of the other codes crash? they all work?

**Comment by Peoples00** [comment]
yes the others work and no crash

**Comment by Yohoki** [comment]
can you press triangle on one of the not working codes and upload a screenshot?

**Comment by Peoples00** [comment]
how do i do it in the game or vitashell?

**Comment by Yohoki** [comment]
PS+Start

**Comment by Yohoki** [comment]
or, just a picture from a phone would work. I just need to be able to read the numbers.

**Comment by Peoples00** [comment]
![2019-03-27-174622](https://user-images.githubusercontent.com/46718103/55095817-10a60b80-50b9-11e9-8c8b-acd9b9db6b82.jpg)

**Comment by Yohoki** [comment]
oh, I'm sorry. In the game, highlight the code and hit triangle, not in vitashell. I'm needing to see the memory view. please keep the code turned off before hitting triangle so I can see unmodified data.

**Comment by Peoples00** [comment]
So should I activate the 2 cheats and when the crash comes make a screenshot?

**Comment by Yohoki** [comment]
No. Leave the code turned off, but hit triangle on them. then take screenshot.

**Comment by Peoples00** [comment]
should I take a screenshot or more?

**Comment by Yohoki** [comment]
just a screenshot is fine. I just want to see what the data looks like in your ram where that code is.

**Comment by Peoples00** [comment]
![2019-03-27-175720](https://user-images.githubusercontent.com/46718103/55096599-8363b680-50ba-11e9-8972-0730d83b5cc7.jpg)
![2019-03-27-180012](https://user-images.githubusercontent.com/46718103/55096600-8363b680-50ba-11e9-8a87-f2695be8f4a1.jpg)

**Comment by Yohoki** [comment]
Ah. The system language has changed the data for some reason. That's new to me. Give me a second and I'll make a German version for those 2.

~~~~
_V0 999999 Dragonball Punkte
$0200 829223E8 000F423F

_V0 999999 Premium Punkte
$0200 829223EC 000F423F
~~~~

**Comment by Peoples00** [comment]
thanks

**Comment by Peoples00** [comment]
you are the best thank you and it works perfect 👍

**Comment by Yohoki** [comment]
Very welcome. Thanks for your support. I'll close this thread now! Message me on GBATemp Forums if anything else comes up.
