### ISSUE TITLE
can you create cheats for disney epic mickey 2: the power of two? 

### ISSUE THREAD

**Issue by Peoples00** [r0ah/vitacheat#63]
hi can you create cheats for disney epic mickey 2: the power of two PCSF00309?

**Comment by Yohoki** [comment]
I made these for my wife, but I haven't uploaded it yet.
~~~~
# PCSF00309 

_V1 Inf Paint
$0200 8642A5A4 42C80000

_V1 Inf Remover
$0200 8642A5CC 42C80000

_V1 Inf HP
$3201 86BEFA48 0000004C
$3300 00000000 00000006

_V0 Currencies
$0000 00000000 00000000

_V1 --Tickets
$0200 8642A61C 000F423F

_V1 --Mickies
$0200 8642A62C 000F423F

_V1 --Papers
$0200 8642A624 000F423F

_V1 --Fabric
$0200 8642A634 000F423F
~~~~

**Comment by Peoples00** [comment]
the cheats are not working

**Comment by Yohoki** [comment]
Shoot. I changed to German again and tried them. Paint and paint remover should still work. Looks like HP has moved, though. I'm sorry. I'll have to take a look at these later. I have to pick my children up from school.

You might try changing system language to english, if codes give too much trouble. I don't know how many games this will effect.

**Comment by Peoples00** [comment]
ok i will try it and you can watch it later in peace?

**Comment by Peoples00** [comment]
I have tried it but also that does not work

**Comment by Yohoki** [comment]
all of them do not work? I think the pointer for HP is wrong, but I need to test it to find another.

**Comment by Peoples00** [comment]
yes all of them do not work

**Comment by Peoples00** [comment]
have you already tested this so found a new pointer?

**Comment by Peoples00** [comment]
any news regarding the codes?

**Comment by Yohoki** [comment]
I've made a new Pointer Searcher program to help with this and I'm writing a tutorial so that the community knows how to use it. I'm using this game to show how to use the program, so when I'm done with the tutorial, there will be a few codes I can upload.

**Comment by Yohoki** [comment]
Can you try this one for hp?
~~~~
_V0 Inf HP (All Languages)
$3202 85682F68 00000000
$3200 00000000 FFFFFF8C
$3300 00000000 00000000
~~~~

**Comment by Peoples00** [comment]
I activated the code but it does not work

**Comment by Yohoki** [comment]
hmmm... What version are you on, maybe?

**Comment by Peoples00** [comment]
1.0 and there is no other version

**Comment by Yohoki** [comment]
is it NND?

**Comment by Peoples00** [comment]
yes i downloaded that from PKGJ

**Comment by Yohoki** [comment]
Well... I have no idea then... I have 13 more possible ones, but that's all I've got left... I don't know how to make it work for you after that... I'm not sure why it's not working.
~~~~
_V0 Generated Code
$3202 85682F64 00000280
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85682F68 00000140
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85682FA0 FFFFFEC0
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85682FA8 FFFFFD80
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85682FAC FFFFFC40
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85682FC8 FFFFFB00
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85682FCC FFFFF9C0
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85682FD0 FFFFF880
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85682FD4 FFFFF740
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85682FD8 FFFFF600
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85682FDC FFFFF4C0
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 85683068 FFFFF260
$3200 00000000 0000004C
$3300 00000000 00000006

_V0 Generated Code
$3202 8568306C FFFFF120
$3200 00000000 0000004C
$3300 00000000 00000006
~~~~

![image](https://user-images.githubusercontent.com/44595371/58409190-2c844a00-8035-11e9-8f91-60a727a57062.png)

**Comment by Peoples00** [comment]
So if it should not go then let it please I do not want to make you work unnecessarily

**Comment by Yohoki** [comment]
Ya, I'm sorry, friend. I'm not sure why this one will not work. Do you have any plugins or mods that might be stopping it from working?

**Comment by Peoples00** [comment]
No Problem,

Plugins yes but no mods

**Comment by Peoples00** [comment]
![2019-05-27-114152](https://user-images.githubusercontent.com/46718103/58411664-139b8900-8075-11e9-8363-6fd8a1ff1633.jpg)
![2019-05-27-114200](https://user-images.githubusercontent.com/46718103/58411665-14341f80-8075-11e9-8d98-25ba087b637f.jpg)
![2019-05-27-114203](https://user-images.githubusercontent.com/46718103/58411666-14341f80-8075-11e9-85f9-65f4593cc0a7.jpg)
![2019-05-27-114207](https://user-images.githubusercontent.com/46718103/58411667-14341f80-8075-11e9-8663-f73054622d34.jpg)
![2019-05-27-114209](https://user-images.githubusercontent.com/46718103/58411668-14341f80-8075-11e9-8dd6-9741414a19fe.jpg)
![2019-05-27-114138](https://user-images.githubusercontent.com/46718103/58411669-14341f80-8075-11e9-9e5b-07cffe7b82b2.jpg)
![2019-05-27-114146](https://user-images.githubusercontent.com/46718103/58411670-14ccb600-8075-11e9-9b08-8b417bfe951b.jpg)

**Comment by Yohoki** [comment]
I've began using a new tool for searching for codes. Here's one more to try. If it works, I'll redo the codes for all languages again.
~~~~
_V0 Inf HP (All Languages)
$3202 85682F98 00000000
$3200 00000000 0000004C
$3300 00000000 00000006
~~~~

**Comment by Peoples00** [comment]
This code works, but you only have 4 lives but it does not work

_V0 Inf HP (All Languages)
$3202 85682F64 00000140
$3200 00000000 FFFFFF8C
$3300 00000000 00000006

**Comment by Peoples00** [comment]
Now only paint and remover is missing then it would be great

**Comment by Yohoki** [comment]
Ok. I'll look into it. My wife is the one that plays it, how many lives is max?

**Comment by Peoples00** [comment]
but if the cheat is already activated and you start the game then there is a crash

The paint and remover are working now and I do not know why

**Comment by Peoples00** [comment]
all other cheats work all at once then it was probably just the hp code

**Comment by Peoples00** [comment]
I have only 6 lives and I think there will be more

**Comment by Yohoki** [comment]
Many games crash if you have cheats activated when they load. It's just not something I can fix. I'm sorry there. But, I'm glad the others are working!

Here's an updated HP code, just changed the 6HP to 255HP. I don't know if it crashes, because I haven't tested it tonight. It's just easy to fix that part.

_V0 Inf HP (All Languages)
$3202 85682F64 00000140
$3200 00000000 FFFFFF8C
$3300 00000000 000000FF

**Comment by Peoples00** [comment]
the code works and the lives do not go down super :)

**Comment by Peoples00** [comment]
thank you for your help you are the best :)

**Comment by Yohoki** [comment]
Good deal! Sorry it took so long. I just discovered a new tool that's MUCH more powerful. I'll close this thread then. If they stop working again, just open it back up or start a new one. :D
