### ISSUE TITLE
Assassin's Creed Liberation (PCSB00074)

### ISSUE THREAD

**Issue by Peoples00** [r0ah/vitacheat#65]
hello could anyone create cheats for assassin's creed liberation (PCSB00074)?

**Comment by Peoples00** [comment]
any news regarding the codes?

**Comment by psvita123** [comment]
I second this, please anyone???

**Comment by DJPois0n** [comment]
I could try a money glitch. Other than that I don’t know what other cheats could this game need.

**Comment by Peoples00** [comment]
money cheat would be really helpful I tried it myself but it does not work

**Comment by DJPois0n** [comment]
@peoples00 could u DM me on twitter? I’ll try to help you out :)

**Comment by feijaojms** [comment]
i have susses in money hacking, the video quality was bad, I hope it helps!
https://www.youtube.com/watch?v=z8OEfUO56dU

**Comment by Peoples00** [comment]
> i have susses in money hacking, the video quality was bad, I hope it helps!
> https://www.youtube.com/watch?v=z8OEfUO56dU

perfect i will try this later

**Comment by ayust83** [comment]
Assassin Creed III Liberation cheatcode PCSE00053 /
PCSB00074

**Comment by ayust83** [comment]
Assassin Creed III Liberation cheatcode PCSE00053 /
PCSB00074
