### ISSUE TITLE
PCSE01153 # Title: Secret of Mana it wont work on me

### ISSUE THREAD

**Issue by Kumokun5** [r0ah/vitacheat#66]
why it wont work on my psvita? ver.6.68 can you help me? thank you sir noob here

**Comment by RikuNoctis** [comment]
Make sure the codes are for the version of the game you are playing. Also, make sure they are also for the version dumped, being either Mai (you shouldn't be using Maidumps nowadays) or NoNpDrm.

It doesn't really matter which version your Vita has (3.68, for example) unless it's 3.60, where you will need to use a previous version of Vitacheat, but that's all.

**Comment by Kumokun5** [comment]
i see thank you..
