### ISSUE TITLE
PCSE00244 Valhalla Knight 3

### ISSUE THREAD

**Issue by sop5930** [r0ah/vitacheat#68]
Hello,
Money,pace,Inf Item code not working.

**Comment by r0ah** [comment]
I'll try to find a more consistent pointer code.

**Comment by Liutenantz** [comment]
> Hello, Money,pace,Inf Item code not working.

Hye. Any update?

**Comment by Liutenantz** [comment]
> I'll try to find a more consistent pointer code.

Hye. I also cannot use this code. Please help
