### ISSUE TITLE
Plants Vs Zombies (PCSE00064) No cooldown with touch disabled

### ISSUE THREAD

**Issue by legomeaker101** [r0ah/vitacheat#69]
Whenever I try to activate the no cooldown cheat it does nothing, is there a specific place to activate it? or is it only available on some levels?
UPDATE: I enabled touch controls and the code started working.

If anyone wants to use code using button controls:
1. open the file in any text editor.
2. search for "815FC1F0" on nonpdrm or "815FC1C0" maidump (without quotation marks).
3. replace the 0 with a 4.

**Comment by legomeaker101** [comment]
After restarting a few times the buttons never worked on nonpdrm, is this a problem on my end or a code issue?

**Comment by yuzukirina98** [comment]
Actually the code work fine, just make the code with the activation button. The code not working in the first start of game if you restart or continues your progress, it only work after play the next level (win it first then the code working on the next level).

**Comment by legomeaker101** [comment]
I know that the code only works on new levels because it worked with touch, the problem comes when I use touch and the original code, the problem arises when I use the buttons with touch disabled.

**Comment by Yohoki** [comment]
Ya, touch controls change the addresses a bit. I added this to the wiki when I found out about it a while back. I put the addresses that need changed into it, but if you dis/enable touch controls, you have to exit the game before you can activate the codes, even if it's the right codes.

For some reason, there's 3 states the game can be in: Touch enabled, Controller enabled, and Recently switched. I supposed I COULD make a code that detects which state the game is in and apply the right code depending on which state it's in. That's just complicated and I'm lazy. If you really want it, I can probably do it, though.

**Comment by legomeaker101** [comment]
I know I have to close the game to play with different codes, but they still don't work (and I don't know why).
