### ISSUE TITLE
Sky Force Anniversary (US and EU)

### ISSUE THREAD

**Issue by Smoker1** [r0ah/vitacheat#7]
Now I know why I was told this game is a Problem. Codes MUST be Turned Off right after Destroying the Boss at the end of the Level, or sometimes, the Game will Crash. Then when you start it up again, the Addresses will ALL be changed. Best to Note this Codes as an Example. However, I did learn this:

Mega-Bombs are ALWAYS 1 Line Codes, usually 8Bit.

Lasers are 2 Codes. 1 for Indicator when Selecting how many you want to start the Level with, and the other for In-Game

Shields are a Problem. Usually 2-3 Codes. Same as Lasers, but added Headache.

Shield Gauge and Ship Health % are Floating Point Values and are Dynamic

Stars Obtained are 1 Line Codes, 32Bit

**Comment by r0ah** [comment]
Sorry for the long hiatus, just saw this now. You can edit the repo because I added you a while back as a contributor :)

**Comment by r0ah** [comment]
I've edited the psv file and added notes.
