### ISSUE TITLE
please cheats PCSE00787  Senran Kagura Estival Versus 1.20      Valkyrie Drive - Bhikkhuni [PCSE00948] (

### ISSUE THREAD

**Issue by psvita369** [r0ah/vitacheat#73]
**Describe your findings**
Add here the clear and concise description of your findings.

ex: "The PCSExxxx.psv worked with NoNpDrm and MaiDump."

**Please complete the following information:**
 - **Your PSVita Firmware version**: 3.60HENkaku/Enso, 3.65Enso/h-encore, 3.68h-encore
 - **ID**: PCSExxxxx
 - **Version**: (the game version, if no update then it's 1.00)
 - **Type**: Vitamin, MaiDump, NoNpDrm, Compatibility Pack

**Comment by Yohoki** [comment]
Try giving a post over at the VitaCheat thread on GBATemp. This is mainly a database to list codes we've all found, so not everyone stops by here.

https://gbatemp.net/threads/vitacheat-finalcheat-database.485343/
