### ISSUE TITLE
Cheat code for Attack on Titan 2 (PCSG01102)

### ISSUE THREAD

**Issue by SkywalkerZero** [r0ah/vitacheat#74]
Hello, can you make cheat code for Aot2? I've been tried to make it recently, and always fails. The game has dynamic code, so can you help me make the cheat? Just for INFINITE MONEY CHEAT please, that's all i want to hack.
I can upload you the savegame (if it helps)

Game (ID) : Attack on Titan 2 (PCSG01102)
Version     : 1.05
Type          : NoNpDrm

**Comment by Yohoki** [comment]
Try giving a post over at the VitaCheat thread on GBATemp. This is mainly a database to list codes we've all found, so not everyone stops by here.

https://gbatemp.net/threads/vitacheat-finalcheat-database.485343/

**Comment by Yohoki** [comment]
This issue is solved on GBATemp. I'll go ahead and close it now. If you need any more help, message us on the GBATemp forums again!

https://gbatemp.net/threads/vitacheat-finalcheat-database.485343/page-129#post-8642847
