### ISSUE TITLE
PSCE00293 Final Fantasy X HD

### ISSUE THREAD

**Issue by Kyokitani** [r0ah/vitacheat#75]
I have issues with the code:
_V0 Have 99x of all items
$4001 8262A96C 00000063
$0070 000000001 00000000
It gives 99 potions for all item slots. I'm at the start of the game at Ruins-Hall.

**Comment by Peoples00** [comment]
Same issue on the EU version PCSB00395
_V0 Have 99x of All Items
$4001 8262A96C 00000063
$0070 00000001 00000000

**Comment by RikuNoctis** [comment]
The code doesn't give you the actual items; it only sets the amount of the ones you currently have to 99.

The potions there is what the game sets on the items slots where there wasn't anything before. I'd recommend loading a previous save until you get at least one of every item so you can safely use this code. Alternatively, you can use FFXED and give yourself (and/or delete those potions from your save) any item you want (do note that FFXED is a save editor, ergo, the process is more "complex" than using vitacheat).
