### ISSUE TITLE
please cheat psvita 3.65 :) 

### ISSUE THREAD

**Issue by psvita369** [r0ah/vitacheat#77]
psvita369maquinax@gmail.com

please (cheat )>Senran Kagura Estival Versus 1.21 PCSB00882 

please cheat )>Valkryie Drive Bhikkhuni EUR PCSE00948

please  cheat)>Bullet Girls Phantasia PCSH10099 
Please, can anyone help me :)

**Comment by Yohoki** [comment]
Try giving a post over at the VitaCheat thread on GBATemp. This is mainly a database to list codes we've all found, so not everyone stops by here.

https://gbatemp.net/threads/vitacheat-finalcheat-database.485343/

You've already been told on #73 that posting to the GBATemp Forum is the best place to ask for codes.
