### ISSUE TITLE
PCSG01179 Catherine Full Body (JPN)

### ISSUE THREAD

**Issue by Cupcake-sama** [r0ah/vitacheat#79]
use of any cheat on this game will crash the whole ps vita system (causing a sudden shutdown)

**Comment by RikuNoctis** [comment]
Maybe this can help?

`$3201 81AB67F4 00000410
$3300 00000000 0000000X

Values for X:
1 - Some white cubes on the floor;
2 - Unmovable cube;
4 - Bolt;
5 - Juice for small jump;
6 - Juice for big jump;
7 - Bell for change unmovable cubes to normal cubes.

Note: You can't see it, but you can use it by pressing "square".
Attention! Cheat codes for cubes (values 1 and 2) not work at the first stage. It will freeze your game.`

As you can see, the first two values may freeze the game on the first stage.

**Comment by Cupcake-sama** [comment]
I'm in mid game stage ~ when I decided to use the cheats ..... any of these codes crashes my game instantly

**Comment by r0ah** [comment]
Thank you for the info. Unfortunately, the cheat was mostly coded by the people at speedfly so there's really nothing we can do because they uses a different techniques.

**Comment by r0ah** [comment]
They're different codes but it's better than nothing I guess.
