### ISSUE TITLE
cheat engine table convert on the same game

### ISSUE THREAD

**Issue by xCorra** [r0ah/vitacheat#81]
There are some games that have the same value addresses on pc and psv (attack on titan 2 for example) and I was wondering how to convert cheat engine table to vitacheat format.

**Comment by Yohoki** [comment]
It's not possible, as far as I've seen. It isn't like the game is an exact copy from PC to PSV... There is some little way the games are compiled is different, which changes the addresses drastically. It really just has to be cracked by someone. 

If you're looking for help doing that, or would like to request some one does it for you, you best bet is over on the forums: https://gbatemp.net/threads/vitacheat-finalcheat-database.485343/
