### ISSUE TITLE
Cheats for Accel World vs Sword Art Online  

### ISSUE THREAD

**Issue by MbayeADargen** [r0ah/vitacheat#9]
Please could you do a .psv file for this game   

Game ID (PCSE1071)
Game version (USA)
Game type (NoNpDrm)

**Comment by r0ah** [comment]
I'll try but I'll have to download the game first.

**Comment by MbayeADargen** [comment]
Thanks man, sorry for the late reply

**Comment by calvinorcia** [comment]
Pls send me the cheat too :)

**Comment by MbayeADargen** [comment]
Bonjour,
Je viens de signer la pétition "Bandai Namco: Release Dragon Ball Game
Project Z for Nintendo Switch" et je souhaitais savoir si vous voudriez
nous aider en ajoutant votre signature.

Notre objectif est d'atteindre 100 signatures et nous avons besoin de plus
de soutiens. Pour en savoir plus et pour signer, c'est ici:

http://chng.it/4Qw2mkmXXN

Merci!
Ahmadou

**Comment by SkylarRhys** [comment]
Can you also send me the cheat please. Thanks man!

**Comment by RomComSnaf** [comment]
Can you send me the cheat too?

**Comment by Ketsui-Nebula** [comment]
Could you send me the cheats too?

**Comment by Paradox9990** [comment]
Can I get those cheats too please

**Comment by Wezaemonzz** [comment]
can i ask for the cheat codes too ty

**Comment by calvinorcia** [comment]
Haha i already finished that games

**Comment by kiri8122** [comment]
Hey! Can I get the cheats too?

**Comment by Cooleststar** [comment]
Is it possible for me to get the cheats as well?
