### ISSUE TITLE
Secret of Mana

### ISSUE THREAD

**Issue by Ledah** [r0ah/vitacheat#94]
~~~~
# ID: PCSB01163
# Title: Secret of Mana
# Region: EUR
# Version: latest
# Type: NoNpDrm
# Code Author: Ledah
# Credits:
# Source: https://github.com/r0ah/vitacheat/blob/master/db/PCSB01163.psv
# Note:
~~~~
_V0 INFINITE CANDY
$3001 81E5FB20 000009E4
$3300 00000000 0000000C

_V0 INFINITE CHOCOLATE
$3001 81E5FB20 000009E8
$3300 00000000 0000000C

_V0 INFINITE ROYAL JAM
$3001 81E5FB20 000009EC
$3300 00000000 0000000C

_V0 INFINITE FEARIE WALNUT
$3001 81E5FB20 000009F0
$3300 00000000 0000000C

_V0 INFINITE MEDICAL HERB
$3001 81E5FB20 000009F4
$3300 00000000 0000000C

_V0 INFINITE CUP OF WISHES
$3001 81E5FB20 000009F8
$3300 00000000 0000000C

_V0 PRIM MP 99
$3002 81E5FB20 00000938
$3000 00000000 00000310
$3300 00000000 00000063

_V0 POPOI MP 99
$3002 81E5FB20 00000938
$3000 00000000 00000500
$3300 00000000 00000063

_V0 RANDI STAMINA
$3202 81E5FB20 00000938
$3200 00000000 00000124
$3300 00000000 00000BB8 - > change value to 2328 to set stamina bar to lv9 ( BB8 is lv2)

_V0 PRIMM STAMINA
$3202 81E5FB20 00000938
$3200 00000000 00000314
$3300 00000000 00000BB8 - > change value to 2328 to set stamina bar to lv9 ( BB8 is lv2)

_V0 POPOI STAMINA
$3202 81E5FB20 00000938
$3200 00000000 00000504
$3300 00000000 00000BB8 - > change value to 2328 to set stamina bar to lv9 ( BB8 is lv2)

**Comment by r0ah** [comment]
Thank you for your contribution. Added to the db.
