### ISSUE TITLE
PCSE00755 Game Breaking Bug With Cheat

### ISSUE THREAD

**Issue by vgpetrescu** [r0ah/vitacheat#95]
There is a game breaking bug for the Digimon Cyber Sleuth Game, but I believe there is a fix for it since the same bug occurs with the same cheat in the Steam version. Having "Max" of the story items stops Mirei from continuing the story-line and essentially the game in Chapter 15. If it were at all possible. Maybe you can add a cheat to turn all story items to 1 instead of 99. This is what I'm basing it off of. It doesn't seem too hard of a fix, but I'm just not familiar enough to implement on my own. Thank you.

Best,

Victor

**Comment by r0ah** [comment]
Hello. Thank you for sharing this info. I didn't know this could happen. Sometimes a game is programmed like this where the game check for item flag the wrong way. I mean, this is like a DRM check however unintentional it was if my assumption is right.

This should be an easy fix but the problem is that while I did the cheat codes, I'm stuck early in the story. I'll try to scourge the internet for a cleared savedata.

**Comment by r0ah** [comment]
I found one. Very nice site btw: https://psvitasaves.xyz/search/saves.php?gameid=PCSE00755&gamename=Digimon%20Story%20Cyber%20Sleuth

**Comment by r0ah** [comment]
What is the name of the item? Also, could you share your savedata?

**Comment by vgpetrescu** [comment]
Thanks for getting back to me so quickly. Here is the backup of the save
file. The name of the items are Harmonious Will and Steel Will. I actually
came across that site trying to figure out a fix for my own save file, it's
definitely a great find. Hope to hear from you soon.

-Victor

**Comment by vgpetrescu** [comment]
I'm looking at the email and I see the Dat file attached. Is that not the
right file?

**Comment by r0ah** [comment]
I don't see the attachment. Idk, it should appear on the email body but it's not there. The dat file must have been filtered by the system.

https://i.imgur.com/B0OpLPB.png

**Comment by vgpetrescu** [comment]
https://drive.google.com/file/d/0B51nss9huJ6XLWg5a0NWcTBjeUFCUjZsMTcxRGJWbWNORW1B/view?usp=drivesdk
this should work fine I think

**Comment by r0ah** [comment]
First, try to use this cheat code first. Activate it and quit the VitaCheat menu. Re-enter the VC menu and deactivate it. Proceed with the story and see if it work.

The code should set all the item value into 1.

~~~~
_V0 Max All Items
$D202 840AD955 00AC85E5
$4001 83F603A4 00000001 #SLOTS: 374 (DEC)
$0176 00000020 00000000 #LAST SLOT: 83F6322C
$D202 841AD955 00AC85E5
$4001 840603A4 00000001
$0176 00000020 00000000 #LAST SLOT: 8406322C
~~~~

***

If that doesn't work then try to redump your savedata again and I'll test it myself.

I've downloaded the savedata `PCSE00755_00002048_00000000.dat` but it's 75.7kb. The file should be around 480kb and it shouldn't have a header like this:

~~~~
PSVB....ã.........#.ßÅ..€-......299c0349c200b4bc
~~~~

You should use savemgr to decrypt the savedata:

* Backup savedata with savemgr
* Open VitaShell and go to `ux0:data/savegames/PCSE00755/SLOT#/`

Then upload the `####.bin` file.

**Comment by r0ah** [comment]
[Here's](https://github.com/d3m3vilurr/vita-savemgr/releases) the link to the save manager.

**Comment by r0ah** [comment]
Also, try checking these links.

* [Reddit: [CYBER SLEUTH] Stuck in Chapter 15 :<](https://www.reddit.com/r/digimon/comments/45cigb/cyber_sleuth_stuck_in_chapter_15/)
* [Gamefaqs: Stuck in Chapter 15 - Bug / Glitch ?](https://gamefaqs.gamespot.com/boards/757436-digimon-story-cyber-sleuth/73280085)

**Comment by vgpetrescu** [comment]
Thank you a bunch for the help. Setting everything to 1 fixed the problem.
It was probably the way key items are checked in that situation like you
said. I'll keep in mind the hex combination for maxing items and setting
them to 1 if a similar problem pops up in the future.

Best,

Victor

**Comment by r0ah** [comment]
That's good to know. I've updated the psv file [PCSE00755](https://github.com/r0ah/vitacheat/blob/master/db/PCSE00755.psv).
