### ISSUE TITLE
Ray gigant can't read memory

### ISSUE THREAD

**Issue by TxXDRAGONXxT** [r0ah/vitacheat#99]
**Note**:
Read the [Troubleshooting](https://github.com/r0ah/vitacheat/wiki/Troubleshooting) page before reporting any issues.

**Describe the issue**
I wanted to to change some value in the game ray gigant but when i open memory i only see red crosses even after restart it is still the same can i get some help

**Please complete the following information:**
 - **Your PSVita Firmware version**: 3.65Enso/h-encore
 - **ID**: PCSE00843
 - **Version**: (the game version 1.00)
 - **Type**: NoNpDrm

**Comment by r0ah** [comment]
You should start [here](https://github.com/r0ah/vitacheat/wiki) and look for the "Pointer Search Tutorials."
